### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by diolan12** [Johann-S/bs-stepper#316]
I'm using CDN and I think I properly followed this plugin according to the [README.md](https://github.com/Johann-S/bs-stepper/blob/master/README.md) example.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
```
```html
<script src="https://cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js"></script>
```
I create Stepper instance with jQuery and Vanilla way, but this always gives me error
```console
util.js:20 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at a (util.js:20:107)
    at new e (index.js:51:7)
    at <anonymous>:1:11
```
My instantiation

jQuery
```js
let stepper = new Stepper($('.bs-stepper')[0])
```
Vanilla
```js
let stepper = new Stepper(document.querySelector('.bs-stepper'))
```

[Edit]
Here's my html element structure, just like in [README.md](https://github.com/Johann-S/bs-stepper/blob/master/README.md).
```html
<div class="bs-stepper">
    <div class="bs-stepper-header" role="tablist">
        <!-- your steps here -->
        <div class="step" data-target="#logins-part">
            <button type="button" class="step-trigger" role="tab" aria-controls="logins-part" id="logins-part-trigger">
                <span class="bs-stepper-circle">1</span>
                <span class="bs-stepper-label">Logins</span>
            </button>
        </div>
        <div class="line"></div>
        <div class="step" data-target="#information-part">
            <button type="button" class="step-trigger" role="tab" aria-controls="information-part"
                id="information-part-trigger">
                <span class="bs-stepper-circle">2</span>
                <span class="bs-stepper-label">Various information</span>
            </button>
        </div>
    </div>
    <div class="bs-stepper-content">
        <!-- your steps content here -->
        <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
        </div>
        <div id="information-part" class="content" role="tabpanel" aria-labelledby="information-part-trigger"></div>
    </div>
</div>
```

**Comment by nelson-k-808** [comment]
You haven’t added the .bs-stepper class to your html tag.

**Comment by diolan12** [comment]
> You haven’t added the .bs-stepper class to your html tag.

Edited the code, yesterday I was using the same code from the readme file.
I tried using both vanilla and jQuery way, and it still didn't find the .bs-stepper class.
Today I try again and it just works, turns out I was including the wrong blade file which didn't contain the stepper element.
Thank you for your response.
